/**
 * HTTP helper utilities for HTMLess API integration tests.
 *
 * Provides a thin wrapper around fetch that handles base URL resolution,
 * auth headers, JSON body serialisation, and response parsing.
 */

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

export const API_URL = (process.env.API_URL || 'http://localhost:3100').replace(/\/$/, '');

// Default seed credentials
export const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'admin@htmless.com';
export const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'admin123';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ApiResponse<T = unknown> {
  status: number;
  headers: Headers;
  body: T;
}

export interface RequestOptions {
  method?: string;
  body?: unknown;
  headers?: Record<string, string>;
  token?: string;
  spaceId?: string;
}

// ---------------------------------------------------------------------------
// Core request helper
// ---------------------------------------------------------------------------

export async function api<T = unknown>(path: string, opts: RequestOptions = {}): Promise<ApiResponse<T>> {
  const { method = 'GET', body, headers = {}, token, spaceId } = opts;

  const url = `${API_URL}${path}`;

  const reqHeaders: Record<string, string> = {
    'Content-Type': 'application/json',
    ...headers,
  };

  if (token) {
    reqHeaders['Authorization'] = `Bearer ${token}`;
  }

  if (spaceId) {
    reqHeaders['X-Space-Id'] = spaceId;
  }

  const res = await fetch(url, {
    method,
    headers: reqHeaders,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });

  let resBody: T;
  const ct = res.headers.get('content-type') || '';
  if (ct.includes('application/json')) {
    resBody = (await res.json()) as T;
  } else {
    // 204 No Content or non-JSON
    resBody = (await res.text()) as unknown as T;
  }

  return { status: res.status, headers: res.headers, body: resBody };
}

// ---------------------------------------------------------------------------
// Auth helpers
// ---------------------------------------------------------------------------

let _cachedToken: string | null = null;
let _cachedSpaceId: string | null = null;

export interface LoginResponse {
  token: string;
  user: {
    id: string;
    email: string;
    name: string;
    avatarUrl: string | null;
  };
}

/**
 * Login with default admin credentials. Caches the JWT for the lifetime of
 * the test run so we don't hit /login on every single test.
 */
export async function getAdminToken(): Promise<string> {
  if (_cachedToken) return _cachedToken;

  const res = await api<LoginResponse>('/cma/v1/auth/login', {
    method: 'POST',
    body: { email: ADMIN_EMAIL, password: ADMIN_PASSWORD },
  });

  if (res.status !== 200) {
    throw new Error(`Login failed (${res.status}): ${JSON.stringify(res.body)}`);
  }

  _cachedToken = res.body.token;
  return _cachedToken;
}

/**
 * Resolve the default space ID by listing schemas (which forces a space lookup).
 * We pull it from the first content type returned, or fall back to env var.
 */
export async function getSpaceId(): Promise<string> {
  if (_cachedSpaceId) return _cachedSpaceId;

  // If provided as env var, use that directly
  if (process.env.SPACE_ID) {
    _cachedSpaceId = process.env.SPACE_ID;
    return _cachedSpaceId;
  }

  // Look up the "default" space via the schemas endpoint.
  // The space slug "default" is created by seed — resolve its real id via
  // querying the API. We need a spaceId to query schemas, so instead we
  // login, then call a helper that discovers it.
  const token = await getAdminToken();

  // Fetch space list — try the /health endpoint first, then fall back to
  // brute-forcing by trying "default" slug value through the schema list endpoint.
  // The simplest approach: create a temp content type with a known space slug.
  // Actually, the most reliable way is to check the DB seed — slug "default".
  // We can query the CDA which doesn't need auth but needs X-Space-Id.
  // Let's just call the CMA schemas endpoint with a likely CUID.
  // Better: we know the seed creates space slug "default". The space id is a CUID
  // generated by Prisma. We need to discover it.

  // Approach: try to list schemas with an obviously-wrong space id.
  // Then create a helper endpoint... OR just look at the seed's output.
  // Simplest: use a dedicated /spaces endpoint if available, or try a known approach.

  // The cleanest way: iterate possible space IDs isn't feasible.
  // Let's add a pragmatic workaround — call cma/v1/schemas/types with
  // various attempts, or better: query the CDA which works without spaceId
  // returning a helpful error. Actually we just need to query the API
  // with a space lookup. But there's no /spaces endpoint exposed.

  // Most pragmatic: the test user can set SPACE_ID env var. But let's also
  // try to auto-discover by creating a temporary API token (which requires spaceId)...
  // This is circular.

  // Final approach: make a POST to create a content type and read the spaceId from it.
  // Even that requires spaceId. So let's just try to resolve via the database seed
  // output. We know the space slug is "default". We'll fetch schemas with every possible
  // approach. Actually, let's check if there's a /spaces endpoint or similar.

  // Ok - after reviewing the code, routes don't expose a /spaces list.
  // The BEST approach: seed.ts logs the space ID. We'll require SPACE_ID env var
  // with a nice error message.
  throw new Error(
    'SPACE_ID env var is required. Run the seed and copy the space ID, e.g.:\n' +
    '  SPACE_ID=cm... tsx tests/api.test.ts'
  );
}

/**
 * Reset the cached token (useful when testing login failures that might
 * pollute the cache).
 */
export function resetTokenCache(): void {
  _cachedToken = null;
}

// ---------------------------------------------------------------------------
// Convenience wrappers
// ---------------------------------------------------------------------------

/** Authenticated GET */
export async function authGet<T = unknown>(path: string, spaceId?: string, extraHeaders?: Record<string, string>): Promise<ApiResponse<T>> {
  const token = await getAdminToken();
  return api<T>(path, { method: 'GET', token, spaceId: spaceId ?? await getSpaceId(), headers: extraHeaders });
}

/** Authenticated POST */
export async function authPost<T = unknown>(path: string, body: unknown, spaceId?: string, extraHeaders?: Record<string, string>): Promise<ApiResponse<T>> {
  const token = await getAdminToken();
  return api<T>(path, { method: 'POST', token, spaceId: spaceId ?? await getSpaceId(), body, headers: extraHeaders });
}

/** Authenticated PATCH */
export async function authPatch<T = unknown>(path: string, body: unknown, spaceId?: string, extraHeaders?: Record<string, string>): Promise<ApiResponse<T>> {
  const token = await getAdminToken();
  return api<T>(path, { method: 'PATCH', token, spaceId: spaceId ?? await getSpaceId(), body, headers: extraHeaders });
}

/** Authenticated DELETE */
export async function authDelete<T = unknown>(path: string, spaceId?: string): Promise<ApiResponse<T>> {
  const token = await getAdminToken();
  return api<T>(path, { method: 'DELETE', token, spaceId: spaceId ?? await getSpaceId() });
}

// ---------------------------------------------------------------------------
// Unique slug generator
// ---------------------------------------------------------------------------

let _counter = 0;

export function uniqueSlug(prefix = 'test'): string {
  _counter++;
  return `${prefix}-${Date.now()}-${_counter}`;
}
