import { prisma } from '../db.js';

/**
 * Generates TypeScript declaration file content from all content types
 * in a space.
 */
export async function generateTypeScript(spaceId: string): Promise<string> {
  const contentTypes = await prisma.contentType.findMany({
    where: { spaceId },
    include: { fields: { orderBy: { sortOrder: 'asc' } } },
    orderBy: { key: 'asc' },
  });

  const lines: string[] = [];

  lines.push('// Auto-generated by HTMLess codegen');
  lines.push('// Do not edit manually');
  lines.push('');

  // BlockInstance type used by richtext fields
  lines.push('export interface BlockInstance {');
  lines.push('  type: string;');
  lines.push('  id?: string;');
  lines.push('  attrs?: Record<string, unknown>;');
  lines.push('  children?: BlockInstance[];');
  lines.push('}');
  lines.push('');

  // Generate an interface for each content type's fields
  for (const ct of contentTypes) {
    const interfaceName = toPascalCase(ct.key) + 'Fields';

    lines.push(`export interface ${interfaceName} {`);

    for (const field of ct.fields) {
      const tsType = fieldTypeToTS(field.type, field.enumValues as string[] | null);
      const optional = field.required ? '' : '?';
      lines.push(`  ${field.key}${optional}: ${tsType};`);
    }

    lines.push('}');
    lines.push('');
  }

  // Entry wrapper type
  lines.push('export interface HtmlessEntry<T = Record<string, unknown>> {');
  lines.push('  id: string;');
  lines.push('  contentType: string;');
  lines.push('  slug: string;');
  lines.push("  status: 'draft' | 'published' | 'scheduled' | 'archived';");
  lines.push('  fields: T;');
  lines.push('  createdAt: string;');
  lines.push('  updatedAt: string;');
  lines.push('}');
  lines.push('');

  // Union type mapping content type keys to their field interfaces
  if (contentTypes.length > 0) {
    lines.push('export type ContentTypeMap = {');
    for (const ct of contentTypes) {
      const interfaceName = toPascalCase(ct.key) + 'Fields';
      lines.push(`  '${ct.key}': ${interfaceName};`);
    }
    lines.push('};');
    lines.push('');

    lines.push(
      'export type TypedEntry<K extends keyof ContentTypeMap = keyof ContentTypeMap> = HtmlessEntry<ContentTypeMap[K]>;',
    );
    lines.push('');
  }

  return lines.join('\n');
}

function fieldTypeToTS(type: string, enumValues: string[] | null): string {
  switch (type) {
    case 'text':
    case 'slug':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'date':
      return 'string';
    case 'richtext':
      return 'BlockInstance[]';
    case 'media':
      return 'string';
    case 'reference':
      return 'string';
    case 'json':
      return 'Record<string, unknown>';
    case 'enum':
      if (enumValues && enumValues.length > 0) {
        return enumValues.map((v) => `'${v}'`).join(' | ');
      }
      return 'string';
    default:
      return 'unknown';
  }
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_]+/g, ' ')
    .replace(/(?:^|\s)\w/g, (match) => match.trim().toUpperCase())
    .replace(/\s/g, '');
}
